spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}
  application:
    name: weather

  jpa:
    open-in-view: false
    properties:
      hibernate:
        use_sql_comments: true

springdoc:
  api-docs:
    path: /api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
    display-request-duration: true
    doc-expansion: none
  default-consumes-media-type: application/json
  default-produces-media-type: application/json

openweather:
  api:
    key: a9e22ab5d292f2ebc32813d4b3ae5ed4
